language: java

sudo: false

addons:
  hosts:
  - db

services:
- docker

install:
- docker build -t database db/.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
- mvn clean

script:
- mvn test -Dtest=com.napier.sem.AppTest

jobs:
  include:
  - stage: unit tests
    install: skip
    jdk: oraclejdk11
    script: mvn test -Dtest=com.napier.sem.AppTest
  - stage: integration tests
    jdk: oraclejdk11
    script: mvn test -Dtest=com.napier.sem.develop.AppIntegrationTest.java
  - stage: Deploy
    install: skip
    jdk: oraclejdk11
    script:
    - echo "Deploying"
    - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: seMethods.jar
      skip_cleanup: true
      on:
        tags: true

stages:
- unit tests
- integration tests
- name: GitHub Release
  if: branch = develop
- name: deploy
  if: branch = develop


after_success:
- bash <(curl -s https://codecov.io/bash)